### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by PolestarWx** [accidental-green/validator-install#3]
Hello,

thank you very much for your work !!

Is CLI install still supported ? because I'm using your script on remote ssh server

Best regards

**Comment by accidental-green** [comment]
Hi, The CLI is still supported and should work well using ssh. Just run validator_install_cli.py rather than validator_install_gui.py

Would be great to hear your thoughts once you've tried it out. Cheers

**Comment by PolestarWx** [comment]
Hello again, tested it and works great. 
During my test I was using older version, before you made GUI available.
I don't knowif the very last version correct it but I noticed that I need to do systemctl enable Nimbus and same for besu to get them start on boot.

Some improvment if you wish to provide it:
- prometheus/grafana
- enable node rest API
- enable nimbus to set fastsync as other client // currently I have modified service file after install to use it
- let user choose data folder // in case we want to use ssd as separate storage

I really like your project as it provide a simple way to setup node but keeping a visibility on what happen // easy debugging

**Comment by accidental-green** [comment]
Thanks for the feedback, I'll try to incorporate those changes in the next version!

**Comment by PolestarWx** [comment]
> Thanks for the feedback, I'll try to incorporate those changes in the next version!

Nice ! Thank you again :)

Also, I noticed that the script only works on amd64 if wi do not modify it by ourself. You should write it in readme that is not working on other platform like arm for now ;)

**Comment by PolestarWx** [comment]
> Thanks for the feedback, I'll try to incorporate those changes in the next version!

Also, Just noticed that I had to enable MEV relay on nimbus with `--payload-builder=true --payload-builder-url=http://127.0.0.1:18550` because enabling MEV with your script seems not to add these parameters to the consensus client :)

Also not sure if we have to open 18550 port on ufw as it's only local communication.
